### PR TITLE
Support timeouts for HTTP requests

### LINKED ISSUE #202: EasyRdf_Http_Client timeout parameter not effective
Hi!

I'm using EasyRdf to load data from an external Linked Data server as part of the process of generating HTML pages on the server. I'm worried about situations where the server responds slowly or not at all. In that case, I'd rather show a page with incomplete data instead of letting the user wait very long or forever for the page to generate.

I can use EasyRdf_Graph::load() to fetch the data, which is very convenient as it handles all the content negotiation stuff automatically. Behind the scenes it uses EasyRdf_Http_Client which has a default timeout of 10 seconds. But it seems that this timeout only applies to the initial connection (it is used as a parameter for fsockopen()). It is not applied if the server quickly accepts the connection but then takes a long time to respond with actual data.

Example code:

```
<?php

require_once 'vendor/autoload.php'; // load EasyRdf via Composer

$starttime = time();
$graph = new EasyRdf_Graph("http://fake-response.appspot.com/?sleep=50");
$graph->load();
echo $graph . "\n";
$endtime = time();
echo "request took " . ($endtime-$starttime) . " seconds.\n";
```

(I'm using the [Fake Response Server](http://www.seanshadmand.com/2012/06/21/fake-response-server-slow-response-time-generator/) by Sean Shadmand to simulate slow responses.)

Output of this script:
```
http://fake-response.appspot.com/?sleep=50
request took 50 seconds.
```

I think this could be fixed using strem_set_timeout() in EasyRdf_Http_Client, though my initial attempts at adding such calls didn't work.

This may be related to issue #133 (it should be easier to provide an alternative HTTP client implementation) and #150 (also appears to be a timeout issue with the HTTP client). But I think everyone would benefit if the default EasyRdf_Http_Client included smarter timeout handling. If you think this would be a good idea, I can try to provide an implementation.

### PR DESCRIPTION
**Pull request by osma**
...where the server takes a long time to answer. Fixes #202

I understand that the current Client code is about to be replaced by Guzzle3, but I needed a quick fix to the timeout problem and I thought I'd share it.

### CODE REVIEW

**Comment by indeyets** [comment]
@osma can you provide test for this? I mean mocked one, not with a real connection of course

**Comment by osma** [comment]
> can you provide test for this? I mean mocked one, not with a real connection of course

Um, what would such a test do? My imagination fails me, I cannot figure out anything useful to test without using a real connection.

**Comment by indeyets** [comment]
@osma we need a test for `if ($info['timed_out']) {` branch. So, mocked stream should set this flag and code should throw exception.

But I just read our code and it is not really mock-friendly here. You'd have to refactor it to do this.

So, I'll accept this patch as-is. thanks. Will merge later today

**Comment by osma** [comment]
Thanks @indeyets . Streams are a PHP native thing, not easy to mock AFAIK. Also I couldn't find a way of asking a stream for its current timeout setting.

You may want to consider the 0.9.x version in #235 as well.

**Comment by indeyets** [comment]
You can "mock" streams by registering "stream handler" for a custom protocol and using it in tests. The problem is, that we explicitly forbid all protocols except `http` and `https`

**Comment by osma** [comment]
@indeyets ah, I see, thanks.

**Comment by indeyets** [comment]
applied as bfe7944ce92f76ac64ee12823c33220f9bca3fc6

**Pull request closed without merging**
