### PR TITLE
Implement the ArrayAccess Interface in Resource

### PR DESCRIPTION
**Pull request by bdecarne**
We are developing a full stack framework to consume triple store data in Symfony2 applications. We use massively EasyRdf to manage resources.

In order to use resources in twig template we need to implement ArrayAccess interface. With this update we can use the resource in template like :

```twig
<h1>{{ resource['rdfs:label'] }}</h1>
```

### CODE REVIEW

**Comment by indeyets** [comment]
I understand your approach and I think that we can accept this patch, but I don't think it should be considered the recommended practice. `Resource` is an "active" model. It would be much better to give "passive" model (`array`, `stdClass`) to twig.

Anyway…

Can you add tests for edge-cases?
What if `offsetGet` is called on non-existent property? What if resource has several labels? what if they are language-tagged? etc.

**Comment by bdecarne** [comment]
I had the testOffsetGetNonExistent test.

I agree that this should not be considered as the recommended practice, but it simply rely upon magic functions. Your objections are applicable to these methods, don't you think ?

**Comment by indeyets** [comment]
@bdecarne absolutely. same applies to magic methods. they are nice for fast demos, but can lead to problems if used in real complex projects. So, as I already said, I'm ok with merging this pull-request.

But I ask you not to advertise such usage in documentation of your bundle. we can try to invent some better approach for you to use :) I'll be glad to help, if you're interested. we can continue this via email

p.s. it's better not to send pull-request from `master` branch of your repo, as you can end with messed tree if pull-requests are applied in different order

**Comment by bdecarne** [comment]
Roger that. Just for information Twig has a method to a better access :

```twig
{{ attribute(me, 'all', ['foaf:knows']) }}
```

But it can be messy when you want access to deep data :

```twig
{{ attribute(attribute(nobel, 'get', ['terms:laureate']), 'get', ['foaf:name']) }}
```

The project will be release on Github in next few days.

**Comment by indeyets** [comment]
aha… it is also possible to call `set` in similar way which is a recipe for disaster :) which is the whole point of my comments. `Resource` shouldn't be directly used as model

**Comment by indeyets** [comment]
merged with minor tweaks

**Comment by njh** [comment]
This was on my todo list, thanks for implementing :)

**Pull request closed without merging**
