### PR TITLE
modify guessFormat to work with SPARQL-style PREFIX and BASE

### PR DESCRIPTION
**Pull request by jaw111**
Do a case-insensitive match for prefix or base at start of the file

### CODE REVIEW

**Comment by njh** [comment]
I don't know if I knew that Turtle allowed missing out the `@`:
https://www.w3.org/TR/turtle/#sec-grammar-grammar

I wonder if it would be better make the `@` optional in the regex using '?'.

It would be good to have some tests for this.
Also, I wonder if there is any chance of false-positives.

**Comment by jaw111** [comment]
I thought about making the `@` optional, but given that the SPARQL `BASE` and `PREFIX` are case-insensitive, whilst `@base` and `@prefix` must be lowercase, I thought it was better to add the extra `elseif` to handle this case.

There is some chance of false positives, for example if the input is N-Triples and a string literal in the first 1024 chars happens to contain "base " or "prefix " or "@base " or "@prefix ", then it would be incorrectly guessed to be Turtle. No big deal in this case as N-Triples can be parsed as Turtle, but one can likely come up with other cases where it may be significant.

I'll extend this PR with some additional tests.

Note: The Turtle parser already handles the SPARQL BASE and PREFIX:

* https://github.com/njh/easyrdf/blob/master/lib/Parser/Turtle.php#L145-L148
* https://github.com/njh/easyrdf/blob/master/lib/Parser/Turtle.php#L164-L167

**Comment by jaw111** [comment]
@njh I've added a few tests for the various prefix and base options taken from example 9 in the [Turtle](http://www.w3.org/TR/turtle/) spec.

**Comment by njh** [comment]
Yup, your comments make sense.

Thanks John!

**Pull request merged**
